### ISSUE TITLE
Change method name to be more fluent

### ISSUE THREAD

**Issue by unicodeveloper** [andela-womokoro/urban_dictionary#6]
Look at the objectives in the checkpoint,.

`read()` should be `find()`, this is more appropriate and understandable. `readAll` should be `getAll`. Implement those changes and also reword your README to reflect the change

**Comment by andela-womokoro** [comment]
Hi Prosper,

I have updated the method names from read() and readAll() to find() and
getAll() respectively.

Thanks for the correction.

On Fri, Oct 16, 2015 at 5:01 PM, Otemuyiwa Prosper <notifications@github.com
> wrote:

> Look at the objectives in the checkpoint,.
>
> read() should be find(), this is more appropriate and understandable.
> readAll should be getAll. Implement those changes and also reword your
> README to reflect the change
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andela-womokoro/urban_dictionary/issues/6>.
>



-- 
*Wilson Omokoro | Software Developer | Andela*
*See what TechCrunch
<http://techcrunch.com/2015/06/25/backed-by-spark-capital-andela-will-develop-a-continent-of-tech-talent/>
and StackOverflow
<http://blog.stackoverflow.com/2015/05/stack-overflow-and-andela-partner-to-provide-education-beyond-borders/>
say
about us!*
(c) +234-803-380-6531 | Andela.com <http://andela.com/>
